name: Deploy to Dev

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Prepare docker compose
        env:
          APP_DEPLOY_NAME: deploy-via-ssh
          APP_DEPLOY_IMAGE: ghcr.io/${{ github.repository }}-app:${{ github.sha }}
          APP_URL: ${{ secrets.APP_URL }}
          APP_PORT: 80
        run: |
          bash scripts/prepare-docker-compose.sh > compose.yml
      - name: Set up SSH key
        run: |
          env
          mkdir -p ~/.ssh
          echo "${{ secrets.ARTIFACT_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ env.ARTIFACT_PORT }} ${{ secrets.ARTIFACT_HOST }} >> ~/.ssh/known_hosts
      - name: Upload docker compose
        run: |
          scp compose.yml -P ${{ env.ARTIFACT_PORT }} ${{ secrets.ARTIFACT_USER }}@${{ secrets.ARTIFACT_HOST }}:/home/${{ secrets.ARTIFACT_USER }}/

      - name: Test SSH
        run: |
          ssh -i ~/.ssh/id_rsa -p ${{ env.ARTIFACT_PORT }} ${{ secrets.ARTIFACT_USER }}@${{ secrets.ARTIFACT_HOST }} docker compose pull
